### ISSUE TITLE
hardware workshopper

### ISSUE THREAD

**Issue by soldair** [rvagg/workshopper#52]
wondering if anyone has started on this. i have some ideas that i think would work but would love to hear opinions. 

IOT is super buzzwordy now but node is for this kind of thing and if there is a way we can get all our ducks quacking alike so whatever hardware someone has they can make it through a workshop that integrates lights, streams, and real hardware i think we could make much win.

i work for a node on the server hardware startup so this is an opportunity to think about the best way to test these things too =)

**Comment by martinheidegger** [comment]
Seems resolved.
