### ISSUE TITLE
Emit pass/fail events on the workshopper instance

### ISSUE THREAD

**Issue by alanshaw** [rvagg/workshopper#60]
Exercises have pass/fail events. It would be cool if the workshopper listened for them and re-emitted them so that I can do things like show growl notifications or broadcast exercise pass to a leaderboard server instead of augmenting each exercise or subclassing.

Can create a pull request if you're amenable.

**Comment by FFAxKenny** [comment]
Issue was fixed in #61 - can we close this? =)
