### ISSUE TITLE
need help testing a new workshopper

### ISSUE THREAD

**Issue by mdunisch** [rvagg/workshopper#64]
I really enjoyed doing all the workshoppers I founded on nodeschool.io so I decided to make my own for **Lo-Dash** (fork of underscore).

You can found it at: https://github.com/mdunisch/lololodash

But now i need your help:
- My english is not the best. Someone maybe can have a 2nd read on all texts (especially the problem.md-files)?
- Please test my workshopper and give me feedback for: 

1.) How is the learning curve? Do you found exercises that are too easy or too hard?
2.) Are the problems understandable - you reach the solution?

If would be awesome if someone have time to help me!

I'll plan to add 2-3 more exercises and than push it to npm and nodeshool.io - but it would really help if someone can check if first ;-)

And if someone have an idea for a new exercise for lodash or a correction of the existing exercises - feel free to make a PR!

**Comment by martinheidegger** [comment]
@nazrhyn  What is the state here?

**Comment by mdunisch** [comment]
Oh sorry - can be closed @nazrhyn helped ma a lot!!!

**Comment by nazrhyn** [comment]
Bitte!
