### ISSUE TITLE
Add preferGlobal property to package.json to indicate CLI nature of this application

### ISSUE THREAD

**Issue by peterblazejewicz** [rvagg/workshopper#79]
I've been turnedown with a similar PR proposal covering QA aspects of application of other project:
https://github.com/hapijs/makemehapi/issues/108#issuecomment-68946155

Can I make a PR and add `preferGlobal` key to this project config file-  so change could be propagated as `proper use` to other projects builds upon this one?

Learnyournode uses 'preferGlobal` key:
https://github.com/rvagg/learnyounode/blob/master/package.json#L38
and it is visible in Nodei.co badge:
![nodei.co badge](https://camo.githubusercontent.com/3153bbce0e3725823473237b4c100797e2f62b95/68747470733a2f2f6e6f6465692e636f2f6e706d2f6c6561726e796f756e6f64652e706e673f646f776e6c6f6164733d747275652626646f776e6c6f616452616e6b3d747275652673746172733d74727565)

Thanks!

**Comment by khalifenizar** [comment]
Though I see your point in that this is a building block for CLI applications, I think the nature of this module in and of itself is *not* for installing and running it as a CLI application. Therefore I'm inclined not to add `preferGlobal`. From the [npm package.json docs](https://docs.npmjs.com/files/package.json#preferglobal):

> preferGlobal
>
> If your package is primarily a command-line application that should be installed globally, then set this value to true to provide a warning if it is installed locally.

That said, I wholeheartedly support adding it to the workshoppers themselves.

**Comment by rvagg** [comment]
agreed, -1 on a `preferGlobal` here, it's not accurate and it'll introduce noise when someone does an `npm install` for any workshopper using this package.

**Comment by peterblazejewicz** [comment]
Thank you guys both!
Closing!
