### ISSUE TITLE
Allow using C-n and C-p instead of up and down arrow keys

### ISSUE THREAD

**Issue by strugee** [rvagg/workshopper#88]
Many applications, particularly console applications, support typing C-n (Ctrl-N) and C-p (Ctrl-P) to go up and down, respectively, instead of using the up and down arrow keys. It would be nice if workshopper did this too, in the menu screen.

**Comment by rvagg** [comment]
this is an issue for https://github.com/substack/terminal-menu as we can't control this from here

we have been discussing forking terminal-menu to do some workshopper-specific things but I don't think we've done anything on this yet (did we @martinheidegger?)

**Comment by strugee** [comment]
Filed substack/terminal-menu#28.
