### ISSUE TITLE
What kind of version bump would you like for 2826b6e + 3168ed4?

### ISSUE THREAD

**Issue by tdd** [rvagg/workshopper#89]
Hey Rod,

I just added a couple i18n-related updates to the repo; not new languages, but more comprehensive data for existing languages (+ a leg up for people to add translations in the example repo).

I'm not in a position to publish the module to npm, obviously, and I wouldn't want to bump the version in the repo in a manner not consistent with your own rules. But can you take a moment to check that out and make the necessary bump and publish?

Thanks!

EDIT

For reference:

* https://github.com/rvagg/workshopper/commit/2826b6eb9f8cc8b6d5f2ebd96c65be2e9b5a3d13
* https://github.com/rvagg/workshopper/commit/3168ed48d58192c53ca1199110ffe5f3443f39a5

by @ralphtheninja

**Comment by tdd** [comment]
Ah, damn, GitHub won't autolink in the issue title. I mean the 2 commits since 2.3.0.

**Comment by rvagg** [comment]
@tdd as a general rule in these shared repos where lots of people have commit access, it's preferable to make all changes via pull request to give others a chance to have input or object.

See https://github.com/rvagg/node-levelup/blob/master/CONTRIBUTING.md as a reference for how I usually encourage this to work.

Also re versioning, leave that to the releaser (me) so the `npm version` workflow with automatic tagging and tag signing still works properly.

**Comment by tdd** [comment]
Hey Rod,

Really good point, cornerstone of GitHub flow. No idea why I skipped that?! Sorry about the hickup. I rolled back `master` 2 steps, checked nothing new had gone in, and put that in its branch then PR'd. This also lets me better introduce the changesets, obviously.

**Comment by tdd** [comment]
Oh, and re: versioning, definitely your job :wink:

**Comment by ralphtheninja** [comment]
:+1: Closing :)
