### ISSUE TITLE
Update terminal-menu to version 2

### ISSUE THREAD

**Issue by finnp** [rvagg/workshopper#97]
Hey,

`terminal-menu` fails on `process.stdin.setRawMode(true);`, when newbies are using cygwin for example. However since version 2, they are not using this anymore, so it's not fixable there. workshopper would need to call the method. Then we could add a check and print a user-friendly error message like "Use another terminal..."

best,
Finn

**Comment by martinheidegger** [comment]
I fixed the menu to work with submenus and pushed it to the workshopper, closing this issue.
